- name: otc_auth
  src: eumel8.otc_auth
- name: otc_cts
  src: eumel8.otc_cts
- name: otc_dns
  src: eumel8.otc_dns
- name: otc_ecs
  src: eumel8.otc_ecs
- name: otc_eip
  src: eumel8.otc_eip
- name: otc_elb
  src: eumel8.otc_elb
- name: otc_evs
  src: eumel8.otc_evs
- name: otc_ims
  src: eumel8.otc_ims
- name: otc_jobs
  src: eumel8.otc_jobs
- name: otc_keypair
  src: eumel8.otc_keypair
- name: otc_obs
  src: eumel8.otc_obs
- name: otc_rds
  src: eumel8.otc_rds
- name: otc_secgroup
  src: eumel8.otc_secgroup
- name: otc_subnet
  src: eumel8.otc_subnet
- name: otc_vpc
  src: eumel8.otc_vpc
- name: os-client-config
  src: eumel8.os-client-config
