---
- hosts: localhost
  gather_facts: no
  vars:
    tenant_ini: "vars/tenant.ini"
    # ECS vars
    availability_zone: "{{ lookup('ini', 'availability_zone section={{ ecs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'availability_zone section=DEFAULT file={{ tenant_ini }}') )}}"
    ecs_adminkey: "{{ lookup('ini', 'ecs_adminkey section={{ ecs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'ecs_adminkey section=DEFAULT file={{ tenant_ini }}') ) }}"
    ecs_volumesize: "{{ lookup('ini', 'ecs_volumesize section={{ ecs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'ecs_volumesize section=DEFAULT file={{ tenant_ini }}') ) }}"
    ecs_volumetype: "{{ lookup('ini', 'ecs_volumetype section={{ ecs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'ecs_volumetype section=DEFAULT file={{ tenant_ini }}') ) }}"
    ecs_ram: "{{ lookup('ini', 'ecs_ram section={{ ecs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'ecs_ram section=DEFAULT file={{ tenant_ini }}') ) }}"
    ecs_vcpus: "{{ lookup('ini', 'ecs_vcpus section={{ ecs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'ecs_vcpus section=DEFAULT file={{ tenant_ini }}') ) }}"
    ecs_ipaddress: "{{ lookup('ini', 'ecs_ipaddress section={{ ecs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'ecs_ipaddress section=DEFAULT file={{ tenant_ini }}') ) }}"
    public_ip_address: "{{ lookup('ini', 'ecs_publicip section={{ ecs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'ecs_publicip section=DEFAULT file={{ tenant_ini }}') ) }}"
    ptr_name: "{{ lookup('ini', 'ecs_publicfqdn section={{ ecs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'ecs_publicfqdn section=DEFAULT file={{ tenant_ini }}') ) }}"
    ttl: "{{ lookup('ini', 'ecs_publicttl section={{ ecs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'ecs_publicttl section=DEFAULT file={{ tenant_ini }}') ) }}"
    eip_bandwidth_name: "{{ lookup('ini', 'eip_bandwidth_name section={{ ecs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'eip_bandwidth_name section=DEFAULT file={{ tenant_ini }}') ) }}"
    eip_bandwidth_size: "{{ lookup('ini', 'eip_bandwidth_size section={{ ecs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'eip_bandwidth_size section=DEFAULT file={{ tenant_ini }}') ) }}"
    image_name: "{{ lookup('ini', 'image_name section={{ ecs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'image_name section=DEFAULT file={{ tenant_ini }}') ) }}"
    keypair_file: "{{ lookup('ini', 'keypair_file section={{ ecs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'keypair_file section=DEFAULT file={{ tenant_ini }}') ) }}"
    secgroups: "{{ lookup('ini', 'secgroups section={{ ecs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'secgroups section=DEFAULT file={{ tenant_ini }}') ) }}"
    secgrouprules: "{{ lookup('ini','{{ secgroup_name }} section=securitygroups file={{ tenant_ini }}') }}"
    subnet_name: "{{ lookup('ini', 'subnet_name section={{ ecs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'subnet_name section=DEFAULT file={{ tenant_ini }}') ) }}"
    subnet_net: "{{ lookup('ini', 'subnet_net section={{ ecs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'subnet_net section=DEFAULT file={{ tenant_ini }}') ) }}"
    subnet_gateway: "{{ lookup('ini', 'subnet_gateway section={{ ecs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'subnet_gateway section=DEFAULT file={{ tenant_ini }}') ) }}"
    subnet_dhcp_enable: "{{ lookup('ini', 'subnet_dhcp_enable section={{ ecs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'subnet_dhcp_enable section=DEFAULT file={{ tenant_ini }}') ) }}"
    subnet_primary_dns: "{{ lookup('ini', 'subnet_primary_dns section={{ ecs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'subnet_primary_dns section=DEFAULT file={{ tenant_ini }}') ) }}"
    subnet_secondary_dns: "{{ lookup('ini', 'subnet_secondary_dns section={{ ecs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'subnet_secondary_dns section=DEFAULT file={{ tenant_ini }}') ) }}"
    vpc_name: "{{ lookup('ini', 'vpc_name section={{ ecs_name }} file={{ tenant_ini }}') }}"
    vpc_net: "{{ lookup('ini', 'vpc_net section={{ ecs_name }} file={{ tenant_ini }}') }}"
    # EVS vars
    evs_availability_zone: "{{ lookup('ini', 'evs_availability_zone section={{ evs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'evs_availability_zone section=DEFAULT file={{ tenant_ini }}') ) }}"
    evs_volume_type: "{{ lookup('ini', 'evs_volume_type section={{ evs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'evs_volume_type section=DEFAULT file={{ tenant_ini }}') ) }}"
    evs_size: "{{ lookup('ini', 'evs_size section={{ evs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'evs_size section=DEFAULT file={{ tenant_ini }}') ) }}"
    evs_multiattach: "{{ lookup('ini', 'evs_multiattach section={{ evs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'evs_multiattach section=DEFAULT file={{ tenant_ini }}') ) }}"
    evs_scsi: "{{ lookup('ini', 'evs_scsi section={{ evs_name }} file={{ tenant_ini }}') | default(lookup('ini', 'evs_scsi section=DEFAULT file={{ tenant_ini }}') ) }}"
    # ELB vars
    admin_state_up: "{{ lookup('ini', 'admin_state_up section={{ elb_name }} file={{ tenant_ini }}') | default(lookup('ini', 'admin_state_up section=DEFAULT file={{ tenant_ini }}') ) }}"
    elb_availability_zone: "{{ lookup('ini', 'elb_availability_zone section={{ elb_name }} file={{ tenant_ini }}') | default(lookup('ini', 'elb_availability_zone section=DEFAULT file={{ tenant_ini }}') ) }}"
    elb_bandwidth: "{{ lookup('ini', 'elb_bandwidth section={{ elb_name }} file={{ tenant_ini }}') | default(lookup('ini', 'elb_bandwidth section=DEFAULT file={{ tenant_ini }}') ) }}"
    elb_type: "{{ lookup('ini', 'elb_type section={{ elb_name }} file={{ tenant_ini }}') | default(lookup('ini', 'elb_type section=DEFAULT file={{ tenant_ini }}') ) }}"
    elb_secgroup_name: "{{ lookup('ini', 'elb_secgroup_name section={{ elb_name }} file={{ tenant_ini }}') | default(lookup('ini', 'elb_secgroup_name section=DEFAULT file={{ tenant_ini }}') ) }}"
    elb_subnet_name: "{{ lookup('ini', 'elb_subnet_name section={{ elb_name }} file={{ tenant_ini }}') | default(lookup('ini', 'elb_subnet_name section=DEFAULT file={{ tenant_ini }}') ) }}"
    elb_vpc_name: "{{ lookup('ini', 'elb_vpc_name section={{ elb_name }} file={{ tenant_ini }}') | default(lookup('ini', 'elb_vpc_name section=DEFAULT file={{ tenant_ini }}') ) }}"
    # ELB listener vars
    listener_protocol: "{{ lookup('ini', 'listener_protocol section={{ listener_name }} file={{ tenant_ini }}') | default(lookup('ini', 'listener_protocol section=DEFAULT file={{ tenant_ini }}') ) }}"
    listener_port: "{{ lookup('ini', 'listener_port section={{ listener_name }} file={{ tenant_ini }}') | default(lookup('ini', 'listener_port section=DEFAULT file={{ tenant_ini }}') ) }}"
    listener_backend_protocol: "{{ lookup('ini', 'listener_backend_protocol section={{ listener_name }} file={{ tenant_ini }}') | default(lookup('ini', 'listener_backend_protocol section=DEFAULT file={{ tenant_ini }}') ) }}"
    listener_backend_port: "{{ lookup('ini', 'listener_backend_port section={{ listener_name }} file={{ tenant_ini }}') | default(lookup('ini', 'listener_backend_port section=DEFAULT file={{ tenant_ini }}') ) }}"
    listener_lb_algorithm: "{{ lookup('ini', 'listener_lb_algorithm section={{ listener_name }} file={{ tenant_ini }}') | default(lookup('ini', 'listener_lb_algorithm section=DEFAULT file={{ tenant_ini }}') ) }}"
    listener_certificate_name: "{{ lookup('ini', 'listener_certificate_name section={{ listener_name }} file={{ tenant_ini }}') | default('') ) }}"
    listener_tcp_timeout: "{{ lookup('ini', 'listener_tcp_timeout section={{ listener_name }} file={{ tenant_ini }}') | default('') }}"
    listener_cookie_timeout: "{{ lookup('ini', 'listener_cookie_timeout section={{ listener_name }} file={{ tenant_ini }}') | default('') }}"
    listener_sticky_session_type: "{{ lookup('ini', 'listener_sticky_session_type section={{ listener_name }} file={{ tenant_ini }}') | default('') }}"
    listener_session_sticky: "{{ lookup('ini', 'listener_session_sticky section={{ listener_name }} file={{ tenant_ini }}') | default('') }}"
    # ELB healthcheck vars
    healthcheck_connect_port: "{{ lookup('ini', 'healthcheck_connect_port section={{ listener_name }} file={{ tenant_ini }}') | default(lookup('ini', 'healthcheck_connect_port section=DEFAULT file={{ tenant_ini }}') ) }}"
    healthcheck_interval: "{{ lookup('ini', 'healthcheck_interval section={{ listener_name }} file={{ tenant_ini }}') | default(lookup('ini', 'healthcheck_interval section=DEFAULT file={{ tenant_ini }}') ) }}"
    healthcheck_protocol: "{{ lookup('ini', 'healthcheck_protocol section={{ listener_name }} file={{ tenant_ini }}') | default(lookup('ini', 'healthcheck_protocol section=DEFAULT file={{ tenant_ini }}') ) }}"
    healthcheck_timeout: "{{ lookup('ini', 'healthcheck_timeout section={{ listener_name }} file={{ tenant_ini }}') | default(0) }}"
    healthcheck_uri: "{{ lookup('ini', 'healthcheck_uri section={{ listener_name }} file={{ tenant_ini }}') | default('') }}"
    unhealthy_threshold: "{{ lookup('ini', 'unhealthy_threshold section={{ listener_name }} file={{ tenant_ini }}') | default(0) }}"
    # ELB backend member vars
    backend_members: "{{ lookup('ini', 'backend_members section={{ listener_name }} file={{ tenant_ini }}') | default('') }}"
    # DNS
    zone_description: "{{ lookup('ini','zone_description section={{ zone_name }} file={{ tenant_ini }}') | default(lookup('ini', 'zone_ttl section=DEFAULT file={{ tenant_ini }}') ) }}"
    zone_type: "{{ lookup('ini','zone_type section={{ zone_name }} file={{ tenant_ini }}') | default(lookup('ini', 'zone_type section=DEFAULT file={{ tenant_ini }}') ) }}"
    zone_email: "{{ lookup('ini','zone_email section={{ zone_name }} file={{ tenant_ini }}') | default(lookup('ini', 'zone_email section=DEFAULT file={{ tenant_ini }}') ) }}"
    zone_ttl: "{{ lookup('ini','zone_ttl section={{ zone_name }} file={{ tenant_ini }}') | default(lookup('ini', 'zone_ttl section=DEFAULT file={{ tenant_ini }}') ) }}"
    zone_records: "{{ lookup('ini','{{ zone_name }} section=dnszonerecords file={{ tenant_ini }}') }}"
   # RDS
    rds_availability_zone: "{{ lookup('ini','rds_availability_zone' section={{ rds_name }} file={{ tenant_ini }}')"
    rds_vpc_name: "{{ lookup('ini','rds_vpc_name' section={{ rds_name }} file={{ tenant_ini }}')"
    rds_secgroup_name: "{{ lookup('ini','rds_secgroup_name' section={{ rds_name }} file={{ tenant_ini }}')"
    rds_subnet_name: "{{ lookup('ini','rds_subnet_name' section={{ rds_name }} file={{ tenant_ini }}')"
    rds_type: "{{ lookup('ini','rds_type' section={{ rds_name }} file={{ tenant_ini }}')"
    rds_version: "{{ lookup('ini','rds_version' section={{ rds_name }} file={{ tenant_ini }}')"
    rds_root_password: "{{ lookup('ini','rds_root_password' section={{ rds_name }} file={{ tenant_ini }}')"
    rds_port: "{{ lookup('ini','rds_port' section={{ rds_name }} file={{ tenant_ini }}')"
    rds_ram: "{{ lookup('ini','rds_ram' section={{ rds_name }} file={{ tenant_ini }}')"
    rds_volume_type: "{{ lookup('ini','rds_volume_type' section={{ rds_name }} file={{ tenant_ini }}')"
    rds_volume_size: "{{ lookup('ini','rds_volume_size' section={{ rds_name }} file={{ tenant_ini }}')"
    rds_backup_time: "{{ lookup('ini','rds_backup_time' section={{ rds_name }} file={{ tenant_ini }}')"
    rds_backup_days: "{{ lookup('ini','rds_backup_days' section={{ rds_name }} file={{ tenant_ini }}')"
    rds_ha_enabled: "{{ lookup('ini','rds_ha_enabled' section={{ rds_name }} file={{ tenant_ini }}')"
    rds_ha_replication_mode: "{{ lookup('ini','rds_ha_replication_mode' section={{ rds_name }} file={{ tenant_ini }}')"

    # playbook action
    localaction: "create"

  roles:
    # create VM
    - role: "otc_auth"
    - role: "otc_vpc"
    - role: "otc_subnet"
    - role: "otc_secgroup"
    - role: "otc_keypair"
    - role: "otc_eip"
    - role: "otc_ecs"
    - role: "otc_dns"
      localaction: "ptrcreate"
    # create internal DNS zone
    - role: "otc_vpc"
      localaction: "router"
    - role: "otc_dns"
      localaction: "create"
